### ISSUE TITLE
Add LanguageClient-neovim

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/vim-vsnip-integ#12]
Is it possible to add [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) support? It the most popular third-party LSP client for vim / neovim.

**Comment by hrsh7th** [comment]
OK, I will support it.
I use vim-lamp or vim-lsp everyday.
I have no environment to use LanguageClient-neovim now so take a little time.

**Comment by Shatur95** [comment]
Thank you! I liked this plugin for LSP more than the others :)
You don't need any dependencies, just clone the repo and execute `install.sh` (this will download the plugin binary).

**Comment by hrsh7th** [comment]
Hm... LanguageClient-neovim's behavior has different behavior rather than other clients.
So bit difficult to support it will take a time.

**Comment by Shatur95** [comment]
Will wait!
Currently [neosnippet.vim](https://github.com/Shougo/neosnippet.vim) works with `LanguageClient-neovim` with the following option:
```vim
let g:neosnippet#enable_complete_done = 1
```
You may interested in it as a reference.

**Comment by hrsh7th** [comment]
Could you try https://github.com/hrsh7th/vim-vsnip-integ/pull/13?

LanguageClient-neovim seems to register snippet body as completion word.
IMO this behavior is not good but anyway works.

**Comment by Shatur95** [comment]
You are super fast, thank you, it works!

**Comment by hrsh7th** [comment]
I don't recommend to use the same key.

But you can use the below setting maybe.

```viml
imap <expr><tab> pumvisible() ? "<Plug>(MUcompleteFwd)" : (vsnip#available(1) ? "<Plug>(vsnip-expand-or-jump)" : "<C-n>")
```

**Comment by hrsh7th** [comment]
Fixed in https://github.com/hrsh7th/vim-vsnip-integ/pull/13
