### ISSUE TITLE
Error Pops Up During Asyncomplete Integration

### ISSUE THREAD

**Issue by jmdevin** [hrsh7th/vim-vsnip-integ#16]
The following error appears the first time the user triggers a completion popup menu to appear:

```
{'throwpint': 'function <SNR>88_on_text_changed_i[7]..<SNR>88_maybe_notify_on_change[6]..<SNR>48_on_change[45]..<SNR>48_trigger[9]..asyncomplete#sources#vsnip#completor'}[12]..vsnip#source#find[2]..vsnip#source#user_snippet#find[4]..vsnip#source#create, line 6', 'exception': 'Vim(for):E474: Invalid argument'}'
```

To reproduce, install:
vim-vsnip
vim-vsnip-integ
asyncomplete.vim
asyncomplete-lsp.vim
vim-lsp

This was tested on a vimscript file using the vim-language-server. The server provides some snippets, which seems to be important, as I could not reproduce this in a python file using a server which does not provide snippets.

**Comment by hrsh7th** [comment]
Thanks you for reporting.
I'll investigate it.

**Comment by hrsh7th** [comment]
@jmdevin Could you put your user snippet files?

The files under `echomsg g:vsnip_snippet_dir`.

**Comment by jmdevin** [comment]
I can, and it looks like that was the issue. I had a file there with some snippets, but I had tried to comment them out with '//'. Taking that away fixed it, I don't get the error popping up now. Here is what the file was:

```json
//{
//    "If Statement": {
//        "prefix": ["if"],
//        "body": ["if $1", "\t$0", "endif"],
//        "description": "An if statement."
//    },
//    "For Loop": {
//        "prefix": ["for"],
//        "body": ["for $1", "\t$0", "endfor"],
//        "description": "A for loop."
//    }
//}
```

My bad. I guess we can close the issue.

**Comment by hrsh7th** [comment]
Thanks you for investigate.

I think we can improve error message.
But I close this issue thanks!
