### ISSUE TITLE
Add support for completion-nvim

### ISSUE THREAD

**Issue by haorenW1025** [hrsh7th/vim-vsnip-integ#18]
Hello, I'm the author of [completion-nvim](https://github.com/haorenW1025/completion-nvim), which is a plugin that aims to be a auto-complete engine for the built-in LSP of neovim. I'd love to find a way to integrate with `vim-vsnip`. I can pass the `complete_item` of lsp in `user_data` for now, can you give me a guide on how to completely integrate with your plugins?

**Comment by hrsh7th** [comment]
Thank you to interest to vsnip!

vsnip-integ aims to cover two use-case.

1. Snippet completion
- listing snippet triggers as completion candidates.

2. Expand LSP style snippet on CompleteDone
- This feature needs providing user data by completion engine.

I will implement 2.
Could you tell me the comoletion-nvim's use_data format?

**Comment by haorenW1025** [comment]
I follow the pattern of this [PR](https://github.com/neovim/neovim/pull/11949/), so you can easily access that by `json_decode`. A small problem is I also have a `completionDone` autocmd in `completion-nvim`, can you just provide a function for me to call? It can be easier for me to manage some stuff.

**Comment by hrsh7th** [comment]
Hm...
If you want to manage CompleteDone by yourself, you can call return 'vsnip_integ#_#on_complete_done_after'.

I think this code is useful for you https://github.com/hrsh7th/vim-vsnip-integ/blob/master/autoload/vsnip_integ/deoplete_lsp.vim#L13.
What do you think of it?

**Comment by haorenW1025** [comment]
Looks good to me! So maybe you just need to modify that to a global function(or a function mapped to `<Plug>`) and I can handle it on my side. Is that possible?

**Comment by hrsh7th** [comment]
Yes possible.
I will provide the api please wait.

**Comment by haorenW1025** [comment]
That's great! Please notify me when you're finished, thanks a lot:)

**Comment by hrsh7th** [comment]
@haorenW1025 Sorry for my delay... I tried to organize `vsnip_integ` code but I give up for now.

Anyway, I've expose `on_complete_done` as public API.
I tried to integrate completion-nvim with vim-vsnip-integ then those works fine on my machine.

I was tested with applying below patch for `completion.lua`.

```lua
      if vim.fn.exists('g:loaded_vsnip_integ') then
        api.nvim_call_function('vsnip_integ#on_complete_done', { { completed_item = complete_item, completion_item = item } })
      end
```

**Comment by hrsh7th** [comment]
![completion-nvim](https://user-images.githubusercontent.com/629908/82080507-a5395600-971f-11ea-8ca1-80811b302860.gif)

**Comment by haorenW1025** [comment]
I've tested it on my side. Works great! Thanks for the clear API:)

**Comment by hrsh7th** [comment]
@haorenW1025 Sorry! Please wait for update completion-nvim.

I want to change API name... `on_complete_done` -> `on_complete_done_for_lsp`.

**Comment by hrsh7th** [comment]
I've updated it.
Sorry for confusing

**Comment by haorenW1025** [comment]
Okay that's fine I haven't updated it.

**Comment by haorenW1025** [comment]
I've updated completion-nvim with vim-vsnip support and also put a link to vim-vsnip in README, thanks for the nice plugins:)

**Comment by hrsh7th** [comment]
Thank you for contacting!
I'm happy to more integratons.

**Comment by Shatur95** [comment]
I tested with the `clangd` with the following configuration:

```lua
nvim_lsp.clangd.setup{
    on_attach = require'diagnostic'.on_attach,
    capabilities = {
      textDocument = {
        completion = {
          completionItem = {
            snippetSupport = true
          }
        }
      }
    },
    init_options = {
      usePlaceholders = true,
      completeUnimported = true
    }
  }
```

But snippets not work. I have the following text instead of completion:
```cpp
    std::vector<${1:typename _Tp}> test;
    test.push_back($0);
````

**Comment by haorenW1025** [comment]
@Shatur95 It requires using `on_attach` for `completion-nvim` too. See the README for `completion-nvim` for example.

**Comment by Shatur95** [comment]
@haorenW1025, sorry, I used `autocmd` for attach. But just now also tried the following:

```lua
  local nvim_lsp = require'nvim_lsp'
  local custom_attach = function()
    require'completion'.on_attach()
    require'diagnostic'.on_attach()
  end

  nvim_lsp.clangd.setup{
    on_attach = custom_attach,
    capabilities = {
      textDocument = {
        completion = {
          completionItem = {
            snippetSupport = true
          }
        }
      }
    },
    init_options = {
      usePlaceholders = true,
      completeUnimported = true
    }
  }
```

But still not works.

**Comment by haorenW1025** [comment]
@Shatur95 Hmm can you post up your config our try with minimum config? Cause it's been working on my side.

**Comment by Shatur95** [comment]
@haorenW1025, I'm very sorry! I had to check it first. The issue was on my side with [pear-tree](https://github.com/tmsvg/pear-tree) plugin.
To solve the issue I used the following configuration:

```vim
let g:completion_confirm_key_rhs = "\<plug>(PearTreeExpand)"

" But also need to use the following from pear-tree side
let g:pear_tree_map_special_keys = 0
imap <BS> <plug>(PearTreeBackspace)
imap <Esc> <plug>(PearTreeFinishExpansion)
```

Now everything works, thank you!
