### ISSUE TITLE
Support for Neovim build-in LSP client + deoplete

### ISSUE THREAD

**Issue by pwntester** [hrsh7th/vim-vsnip-integ#3]
Hi, 

I sent this [PR](https://github.com/Shougo/deoplete-lsp/pull/15) to deoplete-lsp which also includes snippet data in the `completed_item`. It use `user_data` as I think it should be the standard. Since this is also the approach used by `vim-lsc`, all I had to do to enable vsnip to expand lsp snippets was faking that I have `vim-lsc` installed by setting `let g:loaded_lsc = 1`

That works for me, but maybe it would be a good idea to detect `deopleple-lsp` and enable this `standard` processing of the `v:completed_item`. or add a configuration option that is not named `loaded_lsc`

Thanks
A

**Comment by hrsh7th** [comment]
OK, I will implement it.

**Comment by hrsh7th** [comment]
Hm... I think we should add `completion_item` instead of `snippet info` in deoplete-lsp for the future improvements.
 I will try to it first.

**Comment by hrsh7th** [comment]
I've supported in #4.
But it needs https://github.com/Shougo/deoplete-lsp/pull/16.
Please wait.

**Comment by hrsh7th** [comment]
The PR has merged.
