### ISSUE TITLE
Expansion doesn't work anymore for vim-lsc

### ISSUE THREAD

**Issue by jandamm** [hrsh7th/vim-vsnip-integ#31]
Since this [commit (2c3686)](https://github.com/hrsh7th/vim-vsnip-integ/commit/2c3686b64e5f21437ca7addd7c0d77f1fdf65eb9) expansion isn't working anymore.

The reason is that `g:vsnip_integ_disable_on_complete_done` is `v:true`.
Setting it to `v:false` does fix it but I shouldn't have to do this manually, do I?

**Comment by hrsh7th** [comment]
I think you install completion-nvim and vim-lsc.

Currently, on_complete_done is disabled for completion-nvim.

I consider it soon.

**Comment by jandamm** [comment]
No, I don't.

Turns out the issue is that I have `plugin/completion.vim` in my runtime where I set `g:loaded_completion` which makes vsnip-integ think I'd use `completion_nvim`. I'll change this to something else 👍

**Comment by hrsh7th** [comment]
Thank you for your investigation.

I was fixed it.

**Comment by DanielViberg** [comment]
Could you share how you've configured vim-vsnip-integ with vim-lsc.
Seems like it's not working well lately:
https://github.com/yegappan/lsp/issues/182

**Comment by jandamm** [comment]
@DanielViberg, I use neither `vim-lsc` nor `vim-vsnip` anymore.
At some point it worked in my [dotfiles](https://github.com/jandamm/dotfiles) but it might be broken today.
