### ISSUE TITLE
When complete done. Does not expand snippet..

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/vim-vsnip-integ#32]
### Problem

@hrsh7th It works fine befor. just when I update the latest neovim and update plugins. lspsaga is my custom lsp plugin.maybe you can use nvim-lspconfig. 

```vim
set rtp+=~/.cache/vim/dein/repos/github.com/nvim-lua/completion-nvim
set rtp+=~/.cache/vim/dein/repos/github.com/hrsh7th/vim-vsnip
set rtp+=~/.cache/vim/dein/repos/github.com/hrsh7th/vim-vsnip-integ

lua require('lspsaga.saga').create_saga_augroup()

let g:completion_enable_auto_popup      = 1
let g:completion_trigger_on_delete      = 1
let g:completion_auto_change_source     = 1
let g:completion_matching_ignore_case   = 1
let g:completion_enable_snippet = 'vim-vsnip'
let g:completion_chain_complete_list = {
            \ 'default': {
            \   'default': [
            \      {'complete_items': ['lsp', 'snippet']},
            \      {'mode': '<c-n>'},
            \   ],
            \   'string': [
            \      {'complete_items': ['path']},
            \   ],
            \   'comment': [
            \      {'complete_items': ['path']},
            \   ],
            \ },
            \ }

let g:completion_confirm_key = ''
imap <expr> <CR>  pumvisible() ?
            \ complete_info()["selected"] != "-1" ? "\<Plug>(completion_confirm_completion)" : "\<c-e>\<CR>" :
            \ "\<CR>"

function! <SID>check_back_space() abort
    let l:col = col('.') - 1
    return !l:col || getline('.')[l:col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <TAB>
            \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<TAB>" :
            \ completion#trigger_completion()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

augroup my_completion_nvim
    autocmd!
    autocmd BufEnter * lua require'completion'.on_attach()
augroup end

set completeopt=menuone,noinsert,noselect
set shortmess=aoOtTIc
set number
set signcolumn=yes

```

gopls config

```lua
  cmd = {"gopls","--remote=auto"};
  filetypes = {'go','gomod'};
  root_patterns = {'go.mod','.git'};
  -- https://github.com/golang/tools/blob/master/gopls/doc/settings.md#settings
  init_options = {
    usePlaceholders=true;
    completionDocumentation=true;
    completeUnimported=true;
  };

```
### env

```
NVIM v0.5.0-aaaad0f
Build type: Release
LuaJIT 2.0.5

```

### preview:

![after](https://user-images.githubusercontent.com/41671631/98111954-573a2980-1edc-11eb-91cb-4f9f74ccf719.gif)

**Comment by hrsh7th** [comment]
Thank you for your report.

It's weird.
I will investigate it...

**Comment by hrsh7th** [comment]
Ah, I understood the reason.

**Comment by hrsh7th** [comment]
I guess you update neovim recently.
The latest neovim has breaking changes for snippet capability at https://github.com/neovim/neovim/pull/13183 .

I think it should support by vim-vsnip-integ automatically.

So I will create PR for it.

**Comment by glepnir** [comment]
Ok i saw it...tj did not tag me, I ignored this pr

**Comment by glepnir** [comment]
check https://github.com/nvim-lua/completion-nvim/issues/258 .

**Comment by hrsh7th** [comment]
@glepnir Could you test with #33 ?

**Comment by glepnir** [comment]
@hrsh7th  Not fix..

**Comment by hrsh7th** [comment]
@glepnir Sorry... I was overlooked it...

I think we can't register capability automatically.
Currently, nvim-lsp needs to register `snippetSupport` in each users.

**Comment by glepnir** [comment]
yep. I fixed in my custom lsp plugin.

**Comment by glepnir** [comment]
Anyway Thanks. closed.

**Comment by hrsh7th** [comment]
Some LSP client provides `let g:***_snippet_enabled = v:true or v:false` but nvim-lsp doesn't.

vim-lsc
https://github.com/natebosch/vim-lsc/blob/master/plugin/lsc.vim#L18

vim-lsp
https://github.com/hrsh7th/vim-vsnip-integ/blob/master/autoload/vsnip_integ/integration/vimlsp.vim#L14

LanguageClient-neovim
https://github.com/hrsh7th/vim-vsnip-integ/blob/master/autoload/vsnip_integ/integration/lcn.vim#L5

**Comment by hrsh7th** [comment]
Thank you for your report!

**Comment by glepnir** [comment]
Ok  I will talk with tj about this. provide an option will be better.
