### ISSUE TITLE
Adding a LICENSE

### ISSUE THREAD

**Issue by VannTen** [hrsh7th/vim-vsnip-integ#35]
Hi, and thanks for your plugin, it's quite cool :)
Would you mind adding a LICENSE file ?
I suppose you would use MIT as in vim-vsnip itself, but it remains a supposition :)

Thanks :+1:

**Comment by hrsh7th** [comment]
THank you for your suggestion.

I've added a LICENSE file.

https://github.com/hrsh7th/vim-vsnip-integ/blob/master/LICENSE
