### ISSUE TITLE
Support for ALE as LSP client.

### ISSUE THREAD

**Issue by yrammos** [hrsh7th/vim-vsnip-integ#41]
@hrsh7th does this wonderful plugin support [ALE](https://github.com/dense-analysis/ale) as LSP provider? If not, are there plans to do so in the future? Many thanks.

**Comment by hrsh7th** [comment]
I don't familiar with ale.

However, In my rough code reading, Probably, it needs to fix the ale side first because the ale does not provide `LSP's CompletionItem` https://github.com/dense-analysis/ale/blob/master/autoload/ale/completion.vim#L653

**Comment by hrsh7th** [comment]
Also, it should be configurable https://github.com/dense-analysis/ale/blob/01800a23addb52788265e0349f519556dab41301/autoload/ale/lsp.vim#L392

**Comment by yrammos** [comment]
Thank you for the quick reply, will take a look. Closing for now.
