### ISSUE TITLE
add support for asyncomplete

### ISSUE THREAD

**Issue by prabirshrestha** [hrsh7th/vim-vsnip-integ#5]
Examples;
https://github.com/prabirshrestha/asyncomplete-neosnippet.vim
https://github.com/prabirshrestha/asyncomplete-ultisnips.vim

**Comment by hrsh7th** [comment]
Thanks your request.

I've supported in #18.

**Comment by prabirshrestha** [comment]
Awesome!

Verified. Thanks for working on the PR.
