### ISSUE TITLE
yegappan/lsp support?

### ISSUE THREAD

**Issue by normen** [hrsh7th/vim-vsnip-integ#57]
I was wondering if there was plans to support the new Vim9 `yegappan/lsp` LSP plugin at some point?

**Comment by hrsh7th** [comment]
I didn't test this yet but I've implemented.

Could you try with yegappan/lsp ?

**Comment by normen** [comment]
Awesome, lets see, I'll report back!

**Comment by yegappan** [comment]
How do I use this snippet plugin with the LSP plugin?  I installed the vim-snip and vim-vsnip-integ packages and also added the maps described in the README.  I enabled the snippet support in the LSP plugin.  When completing a snippet item from the completion menu, how do I jump between the different parts of the snippet?

**Comment by hrsh7th** [comment]
I don't know what kind of operation you are trying to do.

By introducing vim-vsnip, vim-vsnip-integ and LSP plugin, you can do the following.

1. Run completion via LSP (omnifunc etc.)
2. Select the item containing the snippet and confirm with <C-y>
3. The snippet is expanded
4. vsnip mapping can move snippet tab stop

_google translated_

**Comment by hrsh7th** [comment]
But I didn't check with yegappan/lsp and vim-vsnip-integ. I'll check this.

**Comment by normen** [comment]
> How do I use this snippet plugin with the LSP plugin? I installed the vim-snip and vim-vsnip-integ packages and also added the maps described in the README. I enabled the snippet support in the LSP plugin. When completing a snippet item from the completion menu, how do I jump between the different parts of the snippet?

To get all the functions at once you have to set up a tricky keyboard shortcut. This here allows me to use `<tab>` to open the popup menu, expand snips, jump between snip marks and scroll the popup list. It also allows to use `<C-Space>` to open the popup menu without any preceding characters.

```
" supertab
imap <silent><expr> <TAB>
  \ vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' :
  \ pumvisible() ? "\<C-n>" :
  \ <SID>check_back_space() ? "\<TAB>" :
  \ "\<C-x><C-o>"
imap <silent><expr> <S-TAB>
  \ vsnip#available(-1) ? '<Plug>(vsnip-expand-or-jump)' :
  \ pumvisible() ? "\<C-p>" :
  \ <SID>check_back_space() ? "\<S-TAB>" :
  \ "\<C-x><C-o>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
smap <expr> <Tab>   vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<Tab>'
smap <expr> <S-Tab> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
imap <c-space> <C-x><C-o>

" check if last char is a space (Tab-complete)
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

**Comment by hrsh7th** [comment]
@normen So did you get the correct integration?

**Comment by normen** [comment]
> @normen So did you get the correct integration?
Sorry, I wasn't clear on that. I didn't yet see any snippet entries in the lsp autocomplete popup. I was only answering on how to integrate the two plugins with keyboard shortcuts.

**Comment by yegappan** [comment]
I have committed b09afad1cd6e9396f470ab3084b9bc71efe07c33 to add support for snippet expansion using this plugin.  Let me know if you see any issues.

**Comment by normen** [comment]
Hm, I'm not sure, I don't see any snippets in the popup.. When and where are they supposed to appear exactly? 😅

**Comment by yegappan** [comment]
Did you set the 'snippetSupport' option to v:true?

**Comment by hrsh7th** [comment]
I've confirmed the behavior 👍🏼
