### ISSUE TITLE
Error `pynvim.api.nvim.NvimError: b'Key not found: vsnip_integ_config.deoplete'`

### ISSUE THREAD

**Issue by pwntester** [hrsh7th/vim-vsnip-integ#8]
Hi,

Im getting the following error lately when writing text into any buffer
![imagen](https://user-images.githubusercontent.com/125701/72169986-66da0600-33d0-11ea-9e12-8d4bee404ccb.png)

However `echo g:vsnip_integ_config.deoplete` returns `v:true` so it seems the variable is defined

**Comment by pwntester** [comment]
Seems like the following code fixes the issue:

```
def gather_candidates(self, context):
    config = self.vim.vars['vsnip_integ_config']
    if config and config['deoplete']:
        return self.to_candidates(self.vim.call('vsnip#source#find', context['filetype']))
    return []
```

**Comment by hrsh7th** [comment]
Sorry, It is my failure. Thanks for your contribution.
